import fs from 'node:fs';
import assert from 'node:assert/strict';
import {gzipSync} from 'node:zlib';
const root='dist/client';
const source=JSON.parse(fs.readFileSync('public/research.json'));
const reviews=JSON.parse(fs.readFileSync(root+'/browse-reviews.json'));
const catalog=JSON.parse(fs.readFileSync(root+'/browse-catalog.json'));
const ids=new Set(catalog.rows.map(r=>String(r.productId)));
const expected=Object.entries(source).filter(([id,r])=>ids.has(id)&&(!r.evidenceType||r.evidenceType==='review'));
assert.deepEqual(Object.keys(reviews).sort(),expected.map(([id])=>id).sort());
for(const [id,r]of expected){assert.deepEqual(reviews[id],{evidenceType:'review',summary:r.summary,rating:r.rating,sources:r.sources});}
const paths=fs.readdirSync(root,{recursive:true}).filter(p=>fs.statSync(root+'/'+p).isFile());
const bytes=p=>fs.readFileSync(root+'/'+p);
const gzip=p=>gzipSync(bytes(p)).length;
const css=paths.filter(p=>p.endsWith('.css'));
const js=paths.filter(p=>p.endsWith('.js'));
const measurements={catalogGzip:gzip('browse-catalog.json'),reviewsGzip:gzip('browse-reviews.json'),cssGzip:css.reduce((n,p)=>n+gzip(p),0),jsGzip:js.reduce((n,p)=>n+gzip(p),0)};
assert(measurements.catalogGzip<150000,'Catalog exceeded 150 KB gzip budget');
assert(measurements.reviewsGzip<25000,'Reviews exceeded 25 KB gzip budget');
assert(measurements.cssGzip<15000,'CSS exceeded 15 KB gzip budget');
assert(measurements.jsGzip<300000,'JavaScript exceeded 300 KB gzip budget');
assert(!paths.some(p=>p.endsWith('.map')||p==='_worker.js'||p.includes('.env')),'Unexpected server/debug output in static site');
const html=bytes('index.html').toString();
assert.equal((html.match(/<h1(?:\s|>)/g)||[]).length,1,'Homepage needs one H1');
assert(html.includes('Skip to products')&&html.includes('<noscript>'),'Keyboard/no-JS fallback missing');
assert(html.includes('name="description"')&&html.includes('property="og:title"'),'Metadata missing');
const headers=bytes('_headers').toString().replaceAll('\r\n','\n');
assert(headers.includes('/_next/static/*\n  Cache-Control: public, max-age=31536000, immutable'),'Cache actual generated assets');
assert(headers.includes("default-src 'self'; script-src 'self' 'unsafe-inline' https://static.cloudflareinsights.com"),'CSP must restrict scripts while allowing the static app and Cloudflare Web Analytics');
assert(headers.includes("object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; upgrade-insecure-requests"),'CSP hardening directives missing');
assert(headers.includes('https://bcremixed.ispithotfire.com/*\n  Strict-Transport-Security: max-age=31536000'),'HSTS must apply only to the catalog hostname');
assert(bytes('llms.txt').toString().includes('/catalog'),'Discovery guide must link readable catalog');
console.log('Quality checks passed: review parity, size budgets, static-only output, H1, fallback, metadata and cache path.');
console.log(JSON.stringify(measurements));
